services:
  postgres:
    image: postgres:15
    container_name: quizarena_postgres
    environment:
      POSTGRES_DB: quizarena
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: quizarena_redis
    ports:
      - "6380:6379"
    restart: unless-stopped

volumes:
  postgres_data:
